import '@/styles/globals.css';
import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import {Providers} from './providers';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <Providers themeProps={{attribute: 'class', defaultTheme: 'dark'}}>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
      </Providers>
    </html>
  );
}
